### ISSUE TITLE
missing tests for references

### ISSUE THREAD

**Issue by LinguList** [concepticon/pynorare#19]
Just saw that there is not test if a reference is in fact in the references.

**Comment by LinguList** [comment]
In fact, we even do not have references for all datasets in norare-data. @AnnikaTjuka, we should definitely add references for wikidata, webster, omegawiki, and the like.

**Comment by AnnikaTjuka** [comment]
Sure. I'd suggest to structure the Bibtex as follows:
```
@misc{Wikidata,
  title = {Wikidata},
  url = {https://www.wikidata.org/},
  note = {Accessed: 2020-07-20}
}
```
Or should we use `year` instead of `note`?

**Comment by xrotwang** [comment]
Just implemented a test and get:
```
missing references.bib: ['Baroni2011']
missing references.bib: ['Maciejewski2016']
missing references.bib: ['Hill2015']
missing references.bib: ['Lewis2016']
missing references.bib: ['Yao2017']
```

**Comment by xrotwang** [comment]
Oh, wait. haven't pulled the latest changes.

**Comment by xrotwang** [comment]
ah, so the refs must be looked up in the concepticon refs as well ... will do.
